### ISSUE TITLE
Problem uploading a new rule.

### ISSUE THREAD

**Issue by McMagellan** [heishamon/HeishaMon#481] opened 2024-05-04 13:40 UTC
Sometimes it happens that I cannot upload a rule. 
The Rules window freezes. Apparently the routine cannot find the correct end of the file and the console then shows a message like this: 

Sat May 4 09:29:31 2024 (329783): Reaching end of read. Readlen: 473, Totallen: 533

An excerpt from the console log shows the following:
![Bild 2024-05-04 15_27_02](https://github.com/Egyras/HeishaMon/assets/119176707/ab7f98bb-6838-4b7c-ba69-4912d41e3748)

I have a permanent problem with this attached file. 
[concat Testrule V1.txt](https://github.com/Egyras/HeishaMon/files/15209852/concat.Testrule.V1.txt)

If I change the length of the rule by inserting lines, the upload works. 
This rule only runs on the current beta version #485 (thanks to Igor and CurlyMoo) and includes the new commands @SetCurves, concat and print. The upload process also fails, for example in older versions like 3.2.3 .
.
.
.
.
In addition, I sometimes have the problem that with a longer rule the upload process is aborted with the following message: Too large read. (see middle of picture)
![IMG_7679](https://github.com/Egyras/HeishaMon/assets/119176707/e50a9159-7f7a-4c00-9ee5-470f494d8ff9)

**Comment by IgorYbema** [comment] 2024-05-04 13:43
Yes there is a bug which causes it to not read it when it is a specific length. This bug is fixed but not made to production yet.

**Comment by McMagellan** [comment] 2024-05-04 14:00
Thanks for the quick reply. This error has been bothering me for a long time. Good to hear that a fix is ​​coming. Igor asked me not to post any unrelated topics in the "Update rule library" thread, which is why I'm putting it here and hope it's in the right place.

**Comment by IgorYbema** [comment] 2024-05-04 14:10
That was CurlyMo asking you that, not me :)

**Comment by IgorYbema** [comment] 2024-05-04 14:13
Wait, I didn't read it correctly. You also get the error on the alpha builds? I just tried and indeed the webloading seems to hang using this ruleset.

**Comment by McMagellan** [comment] 2024-05-04 14:25
I'm currently using version Alpha-8aa33db, #485
I just wrote a long-term test program with concat, print and SetCurves with and without numeric values and got the “Too large read” error when uploading. Added two blank lines at the end and it can be loaded. Both loading errors in #485 have definitely not been eliminated.

![IMG_8346](https://github.com/Egyras/HeishaMon/assets/119176707/61e294f6-8812-41fd-bd1d-8a025db8acdc)

**Comment by IgorYbema** [comment] 2024-05-05 09:21
I believe I found it. Took me a few hours. Can you test it? 
https://github.com/IgorYbema/HeishaMon/pull/121#issuecomment-2094701566

And can you share that long rules which causes the 'too long read'? Maybe it is fixed now also, not sure.

**Comment by McMagellan** [comment] 2024-05-05 14:32
I switched to version Alpha-f9b90fd #487.
now you have to be strong. Unfortunately, during the first test as described above, I had the same error as described above. After rebooting and reopening the window and saving with an empty window, the next attempt to load the rule worked. Several subsequent loading processes went smoothly. 
The error can therefore only be reproduced by chance and is probably dependent on the state of the Heishamon internal memory usage.

You asked about the test rule that yesterday said "Too large read!" caused.
After a 20-hour test operation, I reloaded the rule today in the old firmware status #485 and the error no longer occurred and can therefore not be reliably reproduced.
You can see that he was there yesterday in the picture above at the time stamp, May 4th 4:11 p.m.

Attached is the test rule. Again, I think it depends on Heishamon's current internal memory state.

[concat Testrule V2a.txt](https://github.com/Egyras/HeishaMon/files/15213304/concat.Testrule.V2a.txt)

**Comment by IgorYbema** [comment] 2024-05-05 18:19
Ok thanks. Yes I believe that there is still another bug in there which is hard to reproduce but this is much better already.

**Comment by McMagellan** [comment] 2024-05-07 11:21
Today I had the error again when loading a test rule with "Too large read" in version Alpha-afd39aa, #494.
After I reopened the crashed rules window and reloaded the same rule, it worked. this error cannot be reproduced.

![IMG_8361](https://github.com/Egyras/HeishaMon/assets/119176707/416e9292-6223-43a3-b8a7-110844b9b18d)

**Comment by CurlyMoo** [comment] 2024-06-10 15:04
This issue seems to be fixed.

**Closed as completed** 2024-06-10 16:04 UTC
